### ISSUE TITLE
FB7868667: The @AppStorage property wrapper should work in an ObservableObject

### ISSUE THREAD

**Issue by sindresorhus** [feedback-assistant/reports#129]
- **Date:** 2020-07-08
- **Resolution:** Fixed (iOS 14.5)
- **Area:** SwiftUI Framework
- **OS:** macOS 11 beta 2
- **Type:** Suggestion

## Description

The recommendation is to move state to an ObservableObject when you need to share state or when you get a lot of it. However, by doing so, you lose a lot of conveniences, like `@AppStorage`. It would be nice if `@AppStorage` worked in an `ObservableObject` too. Ideally, an `ObservableObject` would support the same update mechanism as a `View` (`DynamicProperty`), so all `View` property wrappers could be reused there. That would also enable making custom property wrappers that updates an ObservableObject, which is also not possible right now. In short, ObservableObject is very inconvenient. I often end up with a mess of Combine publishers.

**Comment by malhal** [comment]
But there is no View for @AppStorage to update in an ObservableObject. Just use UserDefaults directly.

**Comment by sindresorhus** [comment]
@malhal This is just a mirror of the FB. No point in commenting here.

**Comment by sindresorhus** [comment]
> But there is no View for @AppStorage to update in an ObservableObject.

Well, obviously. Hence this FB. It could update the ObservableObject.

> Just use UserDefaults directly.

No thanks. That's verbose and not type-safe.

**Comment by malhal** [comment]
`ObservableObject` isn't designed for view state, I think that's your problem. View state should be stored in View structs using @State and @Binding. Use `ObservableObject` for your data model and for fetchers/loaders.

**Comment by malhal** [comment]
https://developer.apple.com/videos/play/wwdc2020/10040/

_State is designed for transient UI state that is local to a view. In this section, I want to move your attention to designing your model and explain all the tools that SwiftUI provides to you.
Typically, in your app, you store and process data by using a data model that is separate from its UI.
This is when you reach a critical point where you need to manage the life cycle of your data, including persisting and syncing it, handle side-effects, and, more generally, integrate it with existing components.
**This is when you should use ObservableObject.** First, let's take a look at how ObservableObject is defined._

**Comment by sindresorhus** [comment]
> ObservableObject isn't designed for view state

Nothing I've said implies that.

**Comment by sindresorhus** [comment]
I'm aware of how things currently work and when to use what. That doesn't mean it couldn't be better. While views are elegant, I find that when you move state out of view into ObservableObject's it becomes a mess of Combine publisher pipelines and not being able to use convenient APIs like `@AppStorage`. I'm thinking something closer to [renderless components](https://kyleshevlin.com/renderless-components) in the React world.

**Comment by malhal** [comment]
> I find that when you move state out of view into ObservableObject's it becomes a mess of Combine publisher pipelines and not being able to use convenient APIs like `@AppStorage`.

Then why move state out of where it is supposed to be?

https://developer.apple.com/documentation/swiftui/managing-user-interface-state
"Encapsulate view-specific data within your app’s view hierarchy to make your views reusable."

In one of the WWDC video the say we must use View struct as the primary encapsulation of our state. And one of the reasons  is it is needed for SwiftUI's dependency tracking to work correctly.

**Comment by sindresorhus** [comment]
This was fixed in iOS 14.5: https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14_5-release-notes
