### ISSUE TITLE
FB8526225: Missing option to include separate AppIcons for macOS 10 and 11

### ISSUE THREAD

**Issue by chrenn** [feedback-assistant/reports#141]
- **Date:** 2020-08-25
- **Resolution:** Won't Fix
- **Area:** AppKit
- **OS:** macOS 11.0
- **Type:** Incorrect/Unexpected Behavior

## Description

Since Developer Beta 5, the option to include “AppIcon-1016.icns” as a separate superellipse icon for Big Sur (described here: https://twitter.com/stroughtonsmith/status/1278364051572232192) has stopped working. Please consider bringing this back as an officially documented option, since many users on macOS 10.x will probably not appreciate getting unfamiliar icons on updated apps.

**Comment by Unichy** [comment]
Who are you talking about? I never saw anybody talking about this.

**Comment by chrenn** [comment]
**Response from Apple**

Thank you for your feedback, it is noted. Engineering has determined that there are currently no plans to address this issue.

This is expected behavior.  An app can only have one icon, and one identity on the App Store.  We expect users of macOS 10.15 and earlier to see (and be comfortable with) “modern” app icons as part of the general awareness of the new design language permeates.

You can close this feedback by clicking on the "Close Feedback" link. Thank you.
