### ISSUE TITLE
FB8732253: macOS 11 no longer preserves the order of menu bar apps (NSStatusBar items)

### ISSUE THREAD

**Issue by sindresorhus** [feedback-assistant/reports#151]
- **Date:** 2020-09-23
- **Resolution:** Fixed
- **Area:** Menu Bar
- **OS:** macOS 11 beta 8
- **Type:** Incorrect/Unexpected Behavior

## Description

The order of third-party menu bar items are no longer preserved on macOS 11. This is a huge regression and usability issue. Users want the menu bar items to be in the order they defined, but now every menu bar item just shows up at the left of existing menu bar items.

Steps to reproduce:
1. Build and run the attached sample project.
2. Command-drag the menu bar item to a different position.
3. Quit the app
4. Build and run it again.
5. Notice how the menu bar position was not preserved.

Note that the menu bar position is correctly preserved if we set `NSStatusItem#autosaveName`, but according to the docs, this is not required and most apps don’t set it:
> If you do not provide an autosave name for a status item, the system automatically chooses a unique name. - https://developer.apple.com/documentation/appkit/nsstatusitem/1644022-autosavename?changes=latest__9

## Files

[Sample project.zip](https://github.com/feedback-assistant/reports/files/5267851/Sample.project.zip)

**Comment by MeneerRemspoor** [comment]
What a bummer, any idea if it will be compatible in the future?

**Comment by marnovo** [comment]
> **Apple Feedback**
> There are changes in the latest update, build 20C5048k, that may have resolved this issue.
You can see the software build your device is running and check for the latest update by clicking on the Apple logo in the upper left hand corner > About This Mac. If the build is not visible, click on the macOS version, e.g. 10.15.x, to reveal it.

Fixed on macOS 11.1 beta 1 (20C5048k) and continues fixed on beta 2 (20C5061b).
