### ISSUE TITLE
FB9851066: SwiftUI Table should support context menu for rows

### ISSUE THREAD

**Issue by sindresorhus** [feedback-assistant/reports#273]
- **Date:** 2022-01-19
- **Resolution:** Open
- **Area:** SwiftUI Framework
- **OS:** macOS 12.1
- **Type:** Suggestion

## Description

It’s common to want to show some actions when right click a row or a selection of rows. For example, deleting the rows, sharing the rows, etc. I would be great if it was possible to attach a `.rowContextMenu` to `Table` which is then shown when right-clicking one or more rows.

I tried attaching `.contextMenu` to `Table`, but it has the incorrect behavior. It shows even when right-clicking the table headers, it doesn’t highlight the select rows, etc.

**Comment by rj93** [comment]
@sindresorhus did you find a solution to this?

**Comment by sindresorhus** [comment]
It's possible now with macOS 13 and iOS 16:

- For rows: https://developer.apple.com/documentation/swiftui/tablerowcontent/contextmenu(menuitems:)?changes=latest_minor
- For selection: https://developer.apple.com/documentation/swiftui/view/contextmenu(forselectiontype:menu:)?changes=latest_minor
