### ISSUE TITLE
FB7367443: SwiftUI's Button view should support `keyEquivalent` on macOS

### ISSUE THREAD

**Issue by sindresorhus** [feedback-assistant/reports#45]
- **Date:** 2019-10-11
- **Resolution:** Open
- **Area:** SwiftUI Framework
- **OS:** macOS 10.15
- **Type:** Suggestion

## Description

This is needed to be able to set a button as the default button that is triggered when the user presses the Return key, or Esc to dismiss a `.sheet()`.

Currently, I have to wrap NSButton to get this functionality, but I expect such functionality to be part of SwiftUI.

Preferably, the SwiftUI solution should be strongly-typed and accept an enum case instead of a string, as the current NSButton `keyEquivalent` is not very elegant.

https://developer.apple.com/documentation/appkit/nsbutton/1525368-keyequivalent

**Comment by sindresorhus** [comment]
Workaround: https://stackoverflow.com/a/58337529/64949

**Comment by orchetect** [comment]
As of Xcode 12 beta, new methods are exposed on Button() allowing assignment of keyEquivalent. The catch is that they require macOS 10.16 / iOS 14.

Setting as default:

    Button( ... )
        .keyboardShortcut(.defaultAction)

Setting as cancel:

    Button( ... )
        .keyboardShortcut(.cancelAction)
