### ISSUE TITLE
FB13797668: xcodebuild crashes systematically when exporting an archive (segfault)

### ISSUE THREAD

**Issue by macmade** [feedback-assistant/reports#562]
- **Date:** 2024-05-14
- **Resolution:** Closed
- **Area:** Xcode
- **OS:** macOS
- **Type:** Incorrect/Unexpected Behavior
- **Keywords:** xcode, xcodebuild, archive, crash, segfault

### What version of Xcode are you using?
15.4 (15F31d)

### Did you see an error message?
Yes

### What was the error?
Segmentation fault: 11

### What time did the issue occur?
2024-05-14T14:21:53+02:00

### What devices were you using when the issue occurred?
Mac

## Description

With the latest Xcode release (15.4), xcodebuild crashes systematically when exporting an archive, with a segmentation fault.
I've attached the complete crash report.

The archive was also built just before by Xcode 15.4.
Version 15.3 had no problem building and exporting archives.

The invocation is as follows:

    xcodebuild archive -project "Foo.xcodeproj" -scheme "Foo" -archivePath "Foo.xcarchive"
    xcodebuild -exportArchive -archivePath "Foo.xcarchive" -exportPath "some/path" -exportOptionsPlist "ExportOptions.plist"

## Files

[crash.txt](https://github.com/user-attachments/files/17132161/crash.txt)

**Comment by macmade** [comment]
Hello,

Thank you for filing the feedback report. We have deployed the fix. Please verify this issue with iOS 18 Beta 4 and update your bug report with your results by logging into https://feedbackassistant.apple.com/ or by using the Feedback Assistant app.

iOS 18 Beta 4 (Build: 22A5316j)
https://developer.apple.com/download/
Posted Date: July 26, 2024

If resolved, you can close your feedback by choosing the Close Feedback menu item in the Actions pop-up in Feedback Assistant.

If the issue persists, please attach a new sysdiagnose captured in the latest build and attach it to the bug report. Thank you.

iOS sysdiagnose Instructions:
https://developer.apple.com/services-account/download?path=/iOS/iOS_Logs/sysdiagnose_Logging_Instructions.pdf

___________________________________
For a complete list of logging instructions, visit:
https://developer.apple.com/bug-reporting/profiles-and-logs/

We appreciate your feedback and look forward to hear from you.

**Comment by macmade** [comment]
Hello,

Thank you for your message and sorry about the confusion. Please verify this issue with Xcode 16 Beta 4. 

Xcode 16 Beta 4 (16A5211f)
https://developer.apple.com/download/
Posted Date: July 23, 2024

We appreciate your feedback and look forward to hear from you.

**Comment by macmade** [comment]
The crash is no longer present in Xcode 16 Beta 4. Thanks.

**Comment by iccir** [comment]
Workaround: ensure that all keys in `ExportOptions.plist` are present. I had to explicitly add a `provisioningProfiles` with an empty Dictionary to avoid this crash.

```
{
	method = "developer-id";
	signingStyle = manual;
	signingCertificate = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
	provisioningProfiles = {};
	teamID = XXXXXXXXXX;
}
```
